# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fed4c039d6d0a569c3fee863f4120faadabcce2e139d1a35b39134e76898a239f050c9413121912351d7a3dfcbacc3edce72cad5672195a51c3f99df7adbe399

test:
  secret_key_base: 25cb14e0b9d6dad08dba4e39f6f03693276ba76bb78e4b28fc1faa55e05bb5f0f7e7ba09a2cf103638a0f221419fc8ed166da1679bba557f46764092fc3ab3dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
